[package]
name = "floating_bar"
version = "0.2.0"
authors = ["1011X <1011XXXXX@gmail.com>"]
edition = "2018"
description = "Representing rational numbers using the floating-bar number type."

repository = "https://github.com/1011X/floating_bar"
readme = "README.md"

keywords = ["float", "floating", "bar", "rational"]
categories = ["data-structures"]

license = "0BSD"

[dependencies]
gcd = "1.2.0"
integer-sqrt = "0.1.2"
